### ISSUE TITLE
Aligned ASCII Tuple Spacing?

### ISSUE THREAD

**Issue by toobulkeh** [toobulkeh/programming-elixir#4]
Is he using some kind of plugin for this? It would be extremely obnoxious to try to keep OCD-aligned on your own.

```
{ :httpoison, "~> 0.8" },
{ :poison,    "~> 1.5" }
```

**Comment by toobulkeh** [comment]
@drapergeek do you know a plugin that does this? Or what it's called in general?

**Comment by drapergeek** [comment]
>@drapergeek do you know a plugin that does this? Or what it's called in general?

I used to know of something in vim that done that but I haven't used it in forever, I don't like that style personally.

**Comment by toobulkeh** [comment]
Yeah, it doesn't even look like he is consistent about it between examples of his own code. Quite frustrating.
